targets:
  $default:
    builders:
      json_serializable:
        generate_for:
        - lib/models/json_*.dart
        options:
          any_map: false
          checked: true
          create_factory: true
          create_to_json: false
          disallow_unrecognized_keys: true
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
      mockito|mockBuilder:
        generate_for:
        - test/*/*_test.dart
